
services:
  mysql:
    image: mysql:8.0.34
    environment:
      MYSQL_HOST: 127.0.0.1
      MYSQL_ROOT_PASSWORD: admin@A1
      MYSQL_DATABASE: db_final_project
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@A1
    ports:
      - "3306:3306"
    networks:
      - my_final_project
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: admin@A1
    ports:
      - "8080:80"
    networks:
      - my_final_project
    depends_on:
      - mysql

  nodejs:
    build: 
      context: .
      dockerfile: Dockerfile
    # working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "5001:5001"
    depends_on:
      - mysql
    environment:
      - PORT=5001
      - DB_HOST=mysql
      - DB_USER=admin
      - DB_NAME=db_final_project
      - DB_PASSWORD=admin@A1
      - DB_PORT=3306
      - DB_LIMIT=0
      - EMAIL=rizkysyahroni100@gmail.com
      - PASSWORD=kkxrplftlyhffzdn
      - NODE_ENV=development
    networks:
      - my_final_project
    command: npx nodemon server.js

volumes:
  mysql_data:

networks:
  my_final_project:
    name: my_final_project